### DISCUSSION TITLE
Change nav-link color

### DISCUSSION THREAD

**Discussion by KatyPurry** [bootscore/bootscore#208] [Q&A] [answered]
Hello,
I'm trying to change links color on the navbar but I don't understand something.
This is the navbar:

```SCSS
.navbar-nav {
  --bs-nav-link-padding-x: 0;
  --bs-nav-link-padding-y: 0.5rem;
  --bs-nav-link-font-weight: ;
  --bs-nav-link-color: var(--bs-navbar-color);
  --bs-nav-link-hover-color: var(--bs-navbar-hover-color);
  --bs-nav-link-disabled-color: var(--bs-navbar-disabled-color);
  display: flex;
  flex-direction: column;
  padding-left: 0;
  margin-bottom: 0;
  list-style: none;
}
```

I added in `_bscore_variable.scss`:

```SCSS
$navbar-color: $white
```
But it doesn't change color. I also tried `$nav-link-color: $white;` found in https://getbootstrap.com/docs/5.0/components/navs-tabs/#sass but same effect, no change.

Do you know what I'm doing wrong?
