### DISCUSSION TITLE
Show main nav dropdowns on hover

### DISCUSSION THREAD

**Discussion by noyloza** [bootscore/bootscore#224] [Q&A] [answered]
Hello, I would like to change the main menu to show child sections on hover, not on click. Can somebody help me make that change in the code? Thank you

**Comment by crftwrk** [comment, marked as answer]
You must split mobile and lg view, because on touchscreens there is no `:hover`

Do this, snippet goes in your child to `scss/_bscore_custom.scss`:

```scss
// Dropdown in mobile offcanvas-menu always open
@include media-breakpoint-down(lg) {
  #bootscore-navbar .dropdown-menu:not(.navbar .dropdown-menu.dropdown-search) {
    display: block;
  }

  #bootscore-navbar .nav-item .dropdown-menu.invisible {
    visibility: visible;
  }
}

// Dropdown open on hover lg size
@include media-breakpoint-up(lg) {
  #bootscore-navbar .nav-item .dropdown-menu {
    margin-top: 0;
    display: block;
    visibility: hidden;
    opacity: 0;
    transition: .7s;
  }

  #bootscore-navbar .nav-item:hover .dropdown-menu {
    visibility: visible;
    opacity: 1;
  }
}
```

If you want to make the `dropdown-toggle` parent clickable, add following snippet to your child `js/custom.js` inside the `jQuery(function ($) {`...`});` wrapper:

```JS
$('#bootscore-navbar .nav-link.dropdown-toggle').click(function () {
  location.href = this.href;
});
```

Clear browser cache. Does this help?

**Reply by noyloza** [reply]
Thank you very much!

**Reply by noyloza** [reply]
How would I keep the mobile parent menus from already being open? Click or touch to open is fine. Please advise?

**Reply by crftwrk** [reply]
1. Delete the first part:

```scss
// Dropdown in mobile offcanvas-menu always open
@include media-breakpoint-down(lg) {
  #bootscore-navbar .dropdown-menu:not(.navbar .dropdown-menu.dropdown-search) {
    display: block;
  }

  #bootscore-navbar .nav-item .dropdown-menu.invisible {
    visibility: visible;
  }
}
```

2. Wrap jQuery snippet in `matchMedia`

```JS
jQuery(function ($) {

  if (window.matchMedia("(min-width: 992px)").matches) {
    $('#bootscore-navbar .nav-link.dropdown-toggle').click(function () {
      location.href = this.href;
    });
  }

});

```

But you have now two different behaviours. On mobile the dropdown toggle is not clickable to a site while on desktop it is and opens dropdown on hover. So, maybe it's better to delete jQuery snippet completely.
