### DISCUSSION TITLE
Removing Title display: none makes text come under menu

### DISCUSSION THREAD

**Discussion by kangarooo** [bootscore/bootscore#418] [Q&A]
https://www.hostinger.com/tutorials/how-to-hide-page-title-wordpress
Usually need 
.page .entry-title {
display: none;
}
but in booscore need
.page .entry-header {
display: none;
}

Then problem comes- text is under menu
![image](https://user-images.githubusercontent.com/73187/222774840-a7d46f3e-e959-4bcb-8887-69a99ccc1210.png)

**Comment by crftwrk** [comment]
Switched this issue into a discussion, because this is no bug.

> Removing Title display: none makes text come under menu

Of course, thats because the navbar has class `fixed-top`. If you remove the page header, then you have to add margin to the content. For example: 

```css
.page .entry-header {
  display: none;
}

.page #content {
  margin-top: 5rem;
}
```

But you do not need to do this, because there are already 2 blank templates which have no title:

- https://github.com/bootscore/bootscore/blob/main/page-templates/page-blank.php
- https://github.com/bootscore/bootscore/blob/main/page-templates/page-blank-with-container.php

Simply select them in backend and place some `<br>` tags on the top of the page content or add a spacer `<div class="spacer"></div>`. 

```css
.spacer {
  margin-top: 4 rem;
}
```

Solved?
