### DISCUSSION TITLE
Bootstrap grid in gutenburg?

### DISCUSSION THREAD

**Discussion by mindstomedia** [bootscore/bootscore#430] [Q&A]
I'm trying to utilize the bootstrap grid system in my Gutenberg editor.

I created a group in ADDITIONAL CSS CLASS(ES) I gave it row

I introduced an image block and paragraph block and gave them col classes, when I apply col-6 or other sizes it works properly.

<?php the_content(); ?> is wrapped in a container.

I am unable to get these blocks to appear as a row.

**Comment by justinkruit** [comment]
I highly recommend trying out this plugin to get Bootstrap blocks into Gutenberg. I use it on every website I build.
https://wordpress.org/plugins/wp-bootstrap-blocks/

**Comment by crftwrk** [comment]
You can use mixins https://getbootstrap.com/docs/5.3/layout/grid/#mixins

```scss
.wp-block-columns {
  @include make-row();
}

.wp-block-column {
  @include make-col-ready();

  @include media-breakpoint-up(lg) {
    @include make-col(6);
  }

}

:where(.wp-block-columns.is-layout-flex) {
  gap: 0;
}
```

Works fine for `col-*-6` (`50 / 50`) classes https://dev.bootscore.me/theme/gutenberg/.

All other columns (`33 / 66`, `66 / 33`, `33 / 33 / 33`, `25 / 50 / 25`) are done with inline-styles, hard to get in.
