### DISCUSSION TITLE
How do I modify the layout for Adding Items to Cart?

### DISCUSSION THREAD

**Discussion by antforager** [bootscore/bootscore#497] [Q&A] [answered]
I installed a WooCommerce extension (Product-Addons) and it smooshes a big DIV right in front of the Quantity +/- buttons and the submit button. It's too crowded and I need to move things around. What I want to do, is move the quantity div and the submit button to the next row. I'm not sure where to do this. 

Any suggestions will be hugely appreciated.

Cindy

**Comment by crftwrk** [comment, marked as answer]
This should do the trick. Code goes to `_bscore_custom.scss`:

```scss
.woocommerce div.product form.cart {
  display: block;

  div.quantity {
    float: left;
  }

  button.button {
    width: calc(100% - 156px); // Width qty input + margin-right
  }
  
}

```

You should check this on different screen sizes and override media queries if needed.
