### DISCUSSION TITLE
Can SCSS Replace Classes?

### DISCUSSION THREAD

**Discussion by antforager** [bootscore/bootscore#500] [Q&A] [answered]
In some cases, I want to add an additional class to a field and sometimes I want to replace a class with another. Instead of modifying the header.php, could I do this in scss?

Examples:

The red-highlighted text on the left is the default child header.php, and the red-highlighted on the right is what I changed or added.

<img width="972" alt="image" src="https://github.com/bootscore/bootscore/assets/11689112/b88a4fd2-69b6-401d-8de0-29527532ce02">

**Comment by crftwrk** [comment, marked as answer]
Sure, here is a rough example how to target classes inside the `#masthead` wrapper. You need `!important` to override Bootstrap utilities.

- `navbar-secondary` does not exist
- Don't know what you did with `navbar-brand`, but override display utilities with `!important`
- `offcanvas-title` has already `margin-bottom: 0;`, no need to add `mb-0` class 

```scss
#masthead {

  // Navbar bg
  .bg-light {
    background-color: var(--#{$prefix}secondary) !important;
  }

  // Nav links
  .nav-link {
    color: $navbar-dark-color;

    &:hover,
    &:focus {
      color: $navbar-dark-hover-color;
    }

    .active {
      color: $navbar-dark-active-color;
    }
  }

  // Offcanvas
  #offcanvas-navbar {

    .offcanvas-body {
      background-color: var(--#{$prefix}secondary);
    }
  }
}
```

Since bootScore 5.3, `bg-light` classes changed to `bg-body-tertiary`

**Reply by antforager** [reply]
**OOh, ignore the post below because I figured it out!**


	.btn-outline-secondary {
		color: var(--#{$prefix}light) !important;
		border-color: white !important;
	}






Great! It all works except for the button color and button outline are now dark (I didn't include that in the screenshot I pasted above).

This doesn't work:

`    button {
		btn-outline-secondary: var(--#{$prefix}light);
    } `

This doesn't work:

`  button {
		.btn {
			btn-outline-secondary: var(--#{$prefix}light) !important;
		}
    } 
  `
Nor this:

`button#btn {
			btn-outline-secondary: var(--#{$prefix}light) !important;
		}`

<img width="262" alt="image" src="https://github.com/bootscore/bootscore/assets/11689112/c0482262-167a-4f80-97ac-9115e96bb2a6">

Please help!!!

**Comment by antforager** [comment]
[crftwrk](https://github.com/crftwrk) You are so amazing! Thank you, this is really fun.

**Reply by crftwrk** [reply]
Thank you! But your buttons won't work that way because you target all `.btn-outline-secondary` in the document and buttons have a `hover` and `active` state as well. Use `@extend` to make this buttons real light buttons and target them in the header by the `#masthead` selector:

```scss
#masthead .btn-outline-secondary {
  @extend .btn-outline-light;
}
```

You can add this to the loop from my previous comment:

```scss
#masthead {

  // Buttons
  .btn-outline-secondary {
    @extend .btn-outline-light;
  }

  // Navbar bg
  .bg-light {
    background-color: var(--#{$prefix}secondary) !important;
  }

  // Nav links
  .nav-link {
    color: $navbar-dark-color;

    &:hover,
    &:focus {
      color: $navbar-dark-hover-color;
    }

    .active {
      color: $navbar-dark-active-color;
    }
  }

  // Offcanvas
  #offcanvas-navbar {

    .offcanvas-body {
      background-color: var(--#{$prefix}secondary);
    }
  }
}
```
