### DISCUSSION TITLE
Font colors change in new version

### DISCUSSION THREAD

**Discussion by esginmurat** [bootscore/bootscore#504] [Q&A] [answered]
Hello dear friends. Thank you again for the new version of bootscore theme. Now I’m trying the 5.3 version trial on localhost. I set the link color #00bc8c in the dark theme. In light theme, I want to #d13241. However, even though I made additions to the _bscore_variables.scss file under the scss folder, there is no change when I refresh the theme. 

Without using the _bscore_custom.scss file. In summary, I want to change the default value of link colors on bootstrap. I’ll be glad, if you help me.

**Comment by crftwrk** [comment, marked as answer]
Hi

> I made additions to the _bscore_variables.scss file under the scss folder, there is no change when I refresh the theme.

If scssphp stoped compiling, enable the developer mode https://github.com/bootscore/bootscore/issues/228#issuecomment-1227647382.

Bootstrap uses the `primary`color for links and a lighten version in dark-theme. 

`$link-color: $primary;`

`$link-color-dark: tint-color($primary, 40%);`

You should change this values easily in `_bscore_variables.scss`


If you want to have completely different colors in light and dark theme, override them in `_bscore_custom.scss` and add a hover color:

```scss
// Light links
a {
  color: #d13241;

  &:hover {
    color: #a72834;
  }
}

// Dark links
[data-bs-theme="dark"] {
  a {
    color: #00bc8c;

    &:hover {
      color: #32c9a3;
    }
  }
}

```

If you do not want to use SCSS syntax, use usual CSS and add them to `style.css`. But this is not a good idea, use SCSS.

```css
a {
  color: #d13241;
}

a:hover {
  color: #a72834;
}

[data-bs-theme="dark"] a {
  color: #00bc8c;
}

[data-bs-theme="dark"] a:hover {
  color: #32c9a3;
}
```

Does this help?
