### DISCUSSION TITLE
Resize Logo Png

### DISCUSSION THREAD

**Discussion by Mick4801** [bootscore/bootscore#513] [Q&A]
Hello
how can resize png logo?
Thanks

**Comment by crftwrk** [comment]
Hi,

logo uses the size of the image, original svg logo has a height of 27px. Add some CSS to change this to your needs:

```css
#masthead .logo {
  height: 100px;
}
```

For your previous question about the SKU in cart (see that you deleted it). There are several snippets in the web to do this, but all shows them twice. This has nothing to do with the theme. Suggest to roughly solve this with SCSS. Code goes to `_bscore_custom.scss`

```scss
tr.woocommerce-cart-form__cart-item.cart_item {
  .product-name {

    a small,
    br {
      display: none;
    }

    a {
      display: block;
    }
  }
}

```
