### DISCUSSION TITLE
Contact form 7

### DISCUSSION THREAD

**Discussion by dhowai** [bootscore/bootscore#599] [Q&A]
How can I edit the Contact 7 form CSS to avoid having the bootstrap class form-check-inline?

**Comment by crftwrk** [comment]
Simply override the `form-check-inline` styles:

```css
.wpcf7 .form-check-inline {
  display: block;
  margin-right: 0;
}
```
