### DISCUSSION TITLE
Sidebar Left

### DISCUSSION THREAD

**Discussion by zsvendo** [bootscore/bootscore#627] [Q&A]
I need the sidebar to be on the left but I found that if you put order-md-last on line 30 as mentioned in woocommerce.php it would work but it doesn't, in fact just changing the columns.php file removing the order-md-last class , but I don't want to touch the original files. What is the resolution?

**Comment by crftwrk** [comment]
You can roughly override the `order-md-last` class in `_bscore_custom.scss`:

```scss
@include media-breakpoint-up(md) {
  #main .order-md-last {
    order: -1 !important;
  }
}
```

> but I don't want to touch the original files

Overriding template files in child is the proper way to achieve this.
