### DISCUSSION TITLE
Remove sidebar single-product

### DISCUSSION THREAD

**Discussion by zsvendo** [bootscore/bootscore#630] [Q&A] [answered]
### Describe the feature that you'd like

How to remove the sidebar from single-product.php taking up the entire width of the page. I don't want to use a plugin for this

### Why is this feature needed? What problem does it solve?

How to remove the sidebar from single-product.php taking up the entire width of the page. I don't want to use a plugin for this

### Checklist

- [X] I have searched the issues and this feature has not been requested.

**Comment by crftwrk** [comment]
> I don't want to use a plugin for this

In fact, you can't do this without a plugin in a clean way.

If you add a widget to the sidebar, WordPress shows this widget on all pages. `single-product` uses `woocommerce.php`. This file is dynamic. Means if widget is active in sidebar it will be shown, if no widget is active the content will take the entire width. What you have to do is to install a contextual widget plugin like https://wordpress.org/plugins/widget-context/, choose `Hide widget on selected` and `All "Products" posts`.

If you definitely do not want to go this way, only chance is to hide sidebar quick'n dirty in `_bscore_custom.scss`:

```scss
// Hide sidebar
.single-product .col-md-4.col-lg-3 {
  display: none;
}

// Set main content to full width
.single-product .col-md-8.col-lg-9 {
  width: 100%;
}
```
