### DISCUSSION TITLE
Adding static info to each payment method.

### DISCUSSION THREAD

**Discussion by goclimbing** [bootscore/bootscore#944] [Q&A] [answered]
I need to be able to add static info for each payment info (fee and time to ship).  I don't want to over ride the template so looks like jQuery to write it.  Any ideas on another way?

![Screenshot 2025-02-02 at 11 50 55 AM](https://github.com/user-attachments/assets/507e78a7-c067-4c5b-8d23-7b2dfe0633f2)

**Comment by crftwrk** [comment]
If you can't enter it in the backend, why not use `::after` in the `for` label?

```css
label[for="payment_method_cheque"]::after {
  content: "(No fee) Ships in 5 days";
}
```
