### ISSUE TITLE
WC -/+ buttons in variable product

### ISSUE THREAD

**Issue by crftwrk** [bootscore/bootscore#100]
There is a bug with -/+ buttons in variable product page https://dev.bootscore.me/product/variable-product/

@Lo1176 any quick idea how to fix that?

**Comment by justinkruit** [comment]
What's the bug? They work fine on my device.

**Comment by crftwrk** [comment]
<img width="716" alt="Bildschirmfoto 2022-02-14 um 09 23 37" src="https://user-images.githubusercontent.com/51531217/153826672-9158bc4c-1641-4e27-b776-ea96be1162c0.png">

**Comment by crftwrk** [comment]
This solve it, but has to fine-tuned with media queries:

```scss
// Variable products
form.variations_form.cart {
    flex-direction: column;
}

.woocommerce-variation-add-to-cart.variations_button {
    display: flex;
}
```
