### ISSUE TITLE
Sidebar widgets to offcanvas mobile

### ISSUE THREAD

**Issue by ant31zac** [bootscore/bootscore#117]
Hi, is it possible to create a sidebar as an off canvas menu?

**Comment by crftwrk** [comment]
Of course, this is possible. To help you with this, please describe detailed what exactly do you want to do.

**Comment by ant31zac** [comment]
Now the sidebar is added after the content. If it were possible, I would like to add a button at the beginning of the content that opens an offcanvas menu with widgets, similar to the main menu

**Comment by crftwrk** [comment]
That's very simple. Check here https://dev.bootscore.me/2012/01/07/template-sticky/ and resize window to mobile view.

1. Copy `sidebar.php` to your child theme
2. Open `sidebar.php` and replace content:

```php
<?php

/**
 * The sidebar containing the main widget area
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package Bootscore
 */

if (!is_active_sidebar('sidebar-1')) {
  return;
}
?>

<!-- Sidebar order first on mobile devides -->
<div class="col-md-4 col-xxl-3 order-first order-md-last">
  <aside id="secondary" class="widget-area">

    <!-- Offcanvas button, hide on md devices -->
    <button class="btn btn-outline-primary mb-4 w-100 d-md-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvas-sidebar" aria-controls="offcanvas-sidebar">
      <i class="fas fa-bars"></i> Sidebar
    </button>

    <!-- Offcanvas sidebar, hide on md devices -->
    <div class="offcanvas offcanvas-end d-md-none" tabindex="-1" id="offcanvas-sidebar" aria-labelledby="offcanvas-sidebarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvas-sidebarLabel">Sidebar</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <?php dynamic_sidebar('sidebar-1'); ?>
      </div>
    </div>

    <!-- Default sidebar, hide on mobile -->
    <div class="d-none d-md-block">
      <?php dynamic_sidebar('sidebar-1'); ?>
    </div>

  </aside>
</div>
```

- `sidebar.php` contains now 2 sidebars with same widgets
- Sidebar is ordered on top on mobile and right on medium devices.
- Default sidebar is hidden on mobile
- Offcanvas and button is hidden on medium

Solved?

**Comment by ant31zac** [comment]
thanks, problem solved.

**Comment by crftwrk** [comment]
We can add this feature to the theme generally using 5.2.0 responsive offcanvas. https://getbootstrap.com/docs/5.2/components/offcanvas/#responsive

**DEMO**
https://dev.bootscore.me/2012/01/03/template-comments/ and resize browser to mobile view.

**sidebar.php**
```php
<?php

/**
 * The sidebar containing the main widget area
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package Bootscore
 */

if (!is_active_sidebar('sidebar-1')) {
  return;
}
?>
<div class="col-md-4 col-xxl-3 order-first order-md-last">
  <aside id="secondary" class="widget-area">

    <button class="btn btn-outline-primary w-100 mb-4 d-flex d-md-none justify-content-between align-items-center" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebar" aria-controls="sidebar">
      <?php esc_html_e('Sidebar', 'bootscore'); ?> <i class="fa-solid fa-ellipsis-vertical"></i>
    </button>

    <div class="offcanvas-md offcanvas-end" tabindex="-1" id="sidebar" aria-labelledby="sidebarLabel">
      <div class="offcanvas-header bg-light">
        <span class="h5 offcanvas-title" id="sidebarLabel"><?php esc_html_e('Sidebar', 'bootscore'); ?></span>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebar" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body flex-column">
        <?php dynamic_sidebar('sidebar-1'); ?>
      </div>
    </div>

  </aside><!-- #secondary -->
</div>
```

**_admin_bar.scss**
```scss
/*--------------------------------------------------------------
Admin bar
--------------------------------------------------------------*/

// Mobile
@media (max-width: 782px) {

  // Fixed admin-bar
  #wpadminbar {
    position: fixed;
  }

  .logged-in.admin-bar {

    // Push content down when WP admin-bar is visible
    .fixed-top,
    .offcanvas:not(.offcanvas-bottom),
    .offcanvas-sm,
    .offcanvas-md,
    .modal-dialog {
      top: 46px;
    }

    // Adjust modal height
    .modal-fullscreen,
    .modal-fullscreen-sm-down,
    .modal-fullscreen-md-down,
    .modal-fullscreen-lg-down,
    .modal-fullscreen-xl-down,
    .modal-fullscreen-xxl-down {
      height: calc(100% - 46px);
    }
  }
}

// Desktop
@media (min-width: 783px) {
  .logged-in.admin-bar {

    // Push content down when WP admin-bar is visible
    .fixed-top,
    .offcanvas:not(.offcanvas-bottom),
    .offcanvas-lg,
    .offcanvas-xl,
    .offcanvas-xxl,
    .modal-dialog {
      top: 32px;
    }

    // Adjust modal height
    .modal-fullscreen,
    .modal-fullscreen-sm-down,
    .modal-fullscreen-md-down,
    .modal-fullscreen-lg-down,
    .modal-fullscreen-xl-down,
    .modal-fullscreen-xxl-down {
      height: calc(100% - 32px);
    }
  }
}
```

Let me know what do you think.
