### ISSUE TITLE
How is accordion sidebar menu implemented on Bootscore.me?

### ISSUE THREAD

**Issue by sokratesagogo** [bootscore/bootscore#133]
Hi, do you use a plugin/shortcode to implement the sidebar menu on the BootScore.me site e.g. https://bootscore.me/documentation/ ?

**Comment by crftwrk** [comment]
Hi,

docs sidebar is hard coded with 2 additional nav_walker menus inside the accordion for theme and plugin docs. Each menu is used twice, one for mobile and one for medium devices.

Below you will find the file `category-documentation.txt`, so you can see how it's done. Download, rename it to `category.php` and store it in your child's root folder.

[category-documentation.txt](https://github.com/bootscore/bootscore/files/8409085/category-documentation.txt)

Register additional menues in your child's `functions.php` and add some menu-items in the backend:
```php
// Register additional Docs Menus
register_nav_menu('theme-docs', 'Theme Docs');
register_nav_menu('plugin-docs', 'Plugin Docs');
```

Does this help?

**Comment by sokratesagogo** [comment]
Many thanks!

**Comment by sokratesagogo** [comment]
Sorry - is there some CSS to go with that?

**Comment by crftwrk** [comment]
Urgh, yes:

```css
/* Docs Nav */
#accordion-docs-mobile .nav-link,
#accordion-docs .nav-link {
  padding-left: 0;
  padding-right: 0;
  padding-top: 0;
  padding-bottom: 0;
}

.mobile-docs-search {
  width: calc(100% - 44px);
}

.docs-sidebar {
  top: 4.5rem;
  height: calc(100vh - 5rem);
  overflow-y: auto;
  
  /* Sidebar correcting focus overflow-y negative margins */
  margin-right: -0.25rem;
  margin-left: -0.25rem;
  padding-top: 0.25rem;
  padding-right: 0.25rem;
  padding-left: 0.25rem;
}
```
