### ISSUE TITLE
[BUG] Offcanvas text going outside container on mobile.

### ISSUE THREAD

**Issue by DogByteMarketing** [bootscore/bootscore#579]
### Describe the bug

It's happening on all depths and even occurs on the Bootscore website.

### Steps to reproduce

1. Go to https://bootscore.me on mobile
2. Click the hamburger icon
3. Expand one of the sections

### Screenshots and Additional Info

![image](https://github.com/bootscore/bootscore/assets/40912852/147dad24-a677-4756-ac69-6dae9af4063c)

### Website link

https://bootscore.me

**Comment by crftwrk** [comment]
Your screen is very very tiny ;-)

Bootstrap uses 

```css
.dropdown-item {
  white-space: nowrap;
}
```

Because we are following straight Bootstrap, we will not fix this here. It's better to create an issue in Bootstrap, but honestly I don't see any chance that they will do changes in dropdown.

However, you can quickly fix this in your child's `_bscore_custom.scss`:


```scss
@include media-breakpoint-down(md) {
  .offcanvas .dropdown-menu .dropdown-item {
    white-space: normal;
  }
}
```
