### ISSUE TITLE
Submenu opened on the right

### ISSUE THREAD

**Issue by Lo1176** [bootscore/bootscore#67]
Hi 
I'm trying to change the submenus into `.dropend` but it doesn't work well ...
Replacing `.dropdown` by `.dropend` only change the carrot symbol 
I would like to have this kind of sub menu (opened on the right, same size as the main menu) :

<img width="391" alt="Capture d’écran 2022-01-07 à 09 58 13" src="https://user-images.githubusercontent.com/56685868/148520777-455d911c-d5aa-4888-825f-f23fda050863.png">

But I'm still having a dropdown one.
Should I do this ? 👇 

```scss
.navbar-nav .dropdown-menu {
    position: absolute;
}
// and start playing with this ...
.dropdown-menu[data-bs-popper] {
    top: 0;
    left: 280px;
    margin-top: 0;
    height: 300px;
}
```
But the matter with this CSS is when I close the submenu it disappears from the right (that's good) 

<img width="391" alt="Capture d’écran 2022-01-07 à 10 27 10" src="https://user-images.githubusercontent.com/56685868/148522766-13b13313-8f5c-4b62-bf3d-ce3c5e4997db.png">

but it appears under the main link before closing (that's bad).

<img width="391" alt="Capture d’écran 2022-01-07 à 10 00 03" src="https://user-images.githubusercontent.com/56685868/148522628-f2bebb77-e855-482c-8bbf-65c6744042b7.png">

Any idea ? 🙏
