### ISSUE TITLE
[BUG] Dark Mode Plugin

### ISSUE THREAD

**Issue by MrMK0R** [bootscore/bootscore#706]
### Describe the bug

The plugin does not seem to be working in a few ways.

`[bs-dark-mode]`
- Does not close/hide upon changing from light to dark

`[bs-dark-mode-toggle]`
- Does not seem to work at all
- Demo on docs shows a vertical layout, and displays horizontal

### Steps to reproduce

1: Upload Plugin
2: Activate Plugin
3: Followed guide on [bs-dark-mode](https://bootscore.me/documentation/bs-dark-mode/)
3: Add `[bs-dark-mode]` or `[bs-dark-mode-toggle]`
4: Toggle toggle

### Screenshots and Additional Info

I only have a bit of CSS modification in the child theme, the main theme isn't touched, and there are no js errors. Not sure if there is any plugin conflict, but I did end up deactivating all of my plugins and the issue persists.

### Website link

https://shmu.tv/

**Comment by crftwrk** [comment]
Hi,

quickly inspected your site and there is following CSS in `style.css` line `74`:

```css
#coming-soon ul {
  list-style-type: none;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  padding: 0px;
  text-align: justify;
}
```

This targets all `ul` inside the `#coming-soon` wrapper, of course the dark-mode's dropdown `ul` as well. Remove it and plugin works as expected. If you need that styles for all lists but want to exclude the `.dropdown-menu`, simply use the `:not()` selector:

```css
#coming-soon ul:not(.dropdown-menu) {
  list-style-type: none;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  padding: 0px;
  text-align: justify;
}
```

Solved?
