### ISSUE TITLE
Change image in post pagination pseudo-class

### ISSUE THREAD

**Issue by rrrnnn** [bootscore/bootscore#88]
I'm working with the 5.1.3.0 version of the theme / child theme.  

On single posts, the previous_post_link and next_post_link functions a rel=prev and rel=next is added to the code that is being output. I'd rather use a SVG file to display the prev and next buttons rather than the below css pseudo element. 

with rel=prev - this following css is output by bootstrap:
`[rel="prev"]:before {
content: "« "; 
}`

I can't find how to remove this css class anywhere, or edit the two *_post_link functions to give me what I want. If I replace it (in wordpress customiser) with content: " " then my SVG disappears

anyway to remove the rel=prev / rel=next from the theme? I cant find where to work on it in the parent / child's files....

thanks in advance

**Comment by crftwrk** [comment]
Hi,

`content: ""` will empty this, that's why your SVG disappears. Override it by adding the URL to your image there `content: url("path/my-image.svg");` and maybe do some additional styling:

```css
[rel="next"]:after {
  content: url("https://www.svgrepo.com/show/76216/right-thin-chevron.svg");
  display: inline-block;
  width: 10px;
  margin-left: 1rem;
}
```

Do not use the Customizer for your custom styles. Add CSS in `/css/scss/_bscore_custom.scss` in your child-theme for better code.

Does this help?
